### ISSUE TITLE
Samba stopped working, May I re-enable it somehow in the script but leave other options off?

### ISSUE THREAD

**Issue by weems** [SummitRoute/osxlockdown#29]
Samba stopped working to connect to Windows machines on my Local Network, May I re-enable it somehow in the script but leave other options off? Or rather, how may I?

**Comment by 0xdabbad00** [comment]
Currently, I don't have undo commands for actions performed.  To ignore certain rules, you can set `enabled` to `false` for the specific commands.  Some work will be needed to maintain this though when I upgrade osxlockdown, so I am going to try to put out a cleaner solution soon for people to have their own custom profiles (this is issue #13).

For your specific problem, this might have been due to the command "Disable File Sharing".

**Comment by weems** [comment]
Perhaps for future reference if anyone else has this issue, I disabled Firewall and it is working again. I need to customize the OSX rules to allow Samba but block other connections.
